file(GLOB ARCH_SRC
        ${CMAKE_SOURCE_DIR}/arch/x86/boot/header.S
        ${CMAKE_SOURCE_DIR}/arch/x86/tools/relocs_32.c
        ${CMAKE_SOURCE_DIR}/arch/x86/tools/relocs_common.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/mpparse.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/kvmclock.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/paravirt.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/pvclock.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/itmt.c
        ${CMAKE_SOURCE_DIR}/arch/x86/boot/early_serial_console.c
        ${CMAKE_SOURCE_DIR}/arch/x86/boot/copy.S
        ${CMAKE_SOURCE_DIR}/arch/x86/boot/compressed/idt_handlers_64.S
        ${CMAKE_SOURCE_DIR}/arch/x86/boot/compressed/misc.c
        ${CMAKE_SOURCE_DIR}/arch/x86/boot/compressed/piggy.S
        ${CMAKE_SOURCE_DIR}/arch/x86/boot/compressed/string.c
        ${CMAKE_SOURCE_DIR}/arch/x86/boot/compressed/early_serial_console.c
        ${CMAKE_SOURCE_DIR}/arch/x86/boot/compressed/ident_map_64.c
        ${CMAKE_SOURCE_DIR}/arch/x86/boot/compressed/head_64.S
        ${CMAKE_SOURCE_DIR}/arch/x86/boot/compressed/acpi.c
        ${CMAKE_SOURCE_DIR}/arch/x86/boot/compressed/pgtable_64.c
        ${CMAKE_SOURCE_DIR}/arch/x86/boot/compressed/efi.c
        ${CMAKE_SOURCE_DIR}/arch/x86/boot/compressed/efi_mixed.S
        ${CMAKE_SOURCE_DIR}/arch/x86/boot/compressed/cpuflags.c
        ${CMAKE_SOURCE_DIR}/arch/x86/boot/compressed/mkpiggy.c
        ${CMAKE_SOURCE_DIR}/arch/x86/boot/memory.c
        ${CMAKE_SOURCE_DIR}/arch/x86/boot/pm.c
        ${CMAKE_SOURCE_DIR}/arch/x86/boot/cpucheck.c
        ${CMAKE_SOURCE_DIR}/arch/x86/boot/a20.c
        ${CMAKE_SOURCE_DIR}/arch/x86/boot/mkcpustr.c
        ${CMAKE_SOURCE_DIR}/arch/x86/boot/edd.c
        ${CMAKE_SOURCE_DIR}/arch/x86/boot/bioscall.S
        ${CMAKE_SOURCE_DIR}/arch/x86/boot/main.c
        ${CMAKE_SOURCE_DIR}/arch/x86/boot/pmjump.S
        ${CMAKE_SOURCE_DIR}/arch/x86/boot/printf.c
        ${CMAKE_SOURCE_DIR}/arch/x86/boot/cpuflags.c
        ${CMAKE_SOURCE_DIR}/arch/x86/boot/video-mode.c
        ${CMAKE_SOURCE_DIR}/arch/x86/boot/cmdline.c
        ${CMAKE_SOURCE_DIR}/arch/x86/boot/video-vesa.c
        ${CMAKE_SOURCE_DIR}/arch/x86/boot/string.c
        ${CMAKE_SOURCE_DIR}/arch/x86/boot/regs.c
        ${CMAKE_SOURCE_DIR}/arch/x86/boot/tools/build.c
        ${CMAKE_SOURCE_DIR}/arch/x86/boot/video.c
        ${CMAKE_SOURCE_DIR}/arch/x86/boot/tty.c
        ${CMAKE_SOURCE_DIR}/arch/x86/boot/version.c
        ${CMAKE_SOURCE_DIR}/arch/x86/boot/video-vga.c
        ${CMAKE_SOURCE_DIR}/arch/x86/boot/video-bios.c
        ${CMAKE_SOURCE_DIR}/arch/x86/boot/cpu.c
        ${CMAKE_SOURCE_DIR}/arch/x86/boot/compressed/kernel_info.S
        ${CMAKE_SOURCE_DIR}/arch/x86/boot/compressed/error.c
        ${CMAKE_SOURCE_DIR}/arch/x86/boot/compressed/cmdline.c
        ${CMAKE_SOURCE_DIR}/arch/x86/boot/compressed/kaslr.c
        ${CMAKE_SOURCE_DIR}/arch/x86/boot/compressed/idt_64.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/vsmp_64.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/cpu/capflags.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/mmconf-fam10h_64.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/cet.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/tracepoint.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/audit_64.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/callthunks.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/unwind_orc.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/umip.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/pcspeaker.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/uprobes.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/perf_regs.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/check.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/hpet.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/amd_nb.c
        ${CMAKE_SOURCE_DIR}/arch/x86/lib/msr-smp.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/early_printk.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/kvm.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/cpu/debugfs.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/cpu/intel_epb.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/cpu/amd.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/apic/hw_nmi.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/cpu/hypervisor.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/cpu/mshyperv.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/module.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/cpu/vmware.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/cpu/perfctr-watchdog.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/kprobes/opt.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/cpu/microcode/amd.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/cpu/zhaoxin.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/crash.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/cpu/mtrr/cleanup.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/cpu/mce/amd.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/cpu/mce/threshold.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/cpu/microcode/intel.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/cpu/mtrr/generic.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/kprobes/core.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/cpu/mce/genpool.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/cpu/mce/intel.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/cpu/microcode/core.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/cpu/mtrr/mtrr.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/cpu/mtrr/if.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/cpu/mce/core.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/apic/probe_64.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/apic/msi.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/cpu/mce/severity.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/apic/apic_flat_64.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/crash_dump_64.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/relocate_kernel_64.S
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/rethook.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/apic/io_apic.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/machine_kexec_64.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/apic/vector.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/apic/ipi.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/vmcore_info_64.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/cpu/centaur.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/apic/init.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/cpu/hygon.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/cpu/feat_ctl.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/apic/apic.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/apic/apic_common.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/apic/apic_noop.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/trace.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/trace_clock.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/cpu/tsx.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/smp.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/fpu/core.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/smpboot.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/cpu/aperfmperf.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/cpu/intel.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/cpu/topology.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/cpu/cpuid-deps.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/cpu/proc.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/cpu/powerflags.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/tsc_sync.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/setup_percpu.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/cpu/umwait.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/acpi/madt_playdead.S
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/acpi/cstate.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/early-quirks.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/cpu/bugs.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/cpuid.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/cpu/match.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/reboot.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/cpu/rdrand.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/msr.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/acpi/boot.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/cpu/topology_ext.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/cpu/common.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/cpu/topology_amd.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/acpi/madt_wakeup.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/acpi/sleep.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/acpi/wakeup_64.S
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/acpi/cppc.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/cpu/topology_common.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/i8237.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/stacktrace.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/cpu/scattered.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/cpu/cacheinfo.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/fpu/xstate.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/step.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/tls.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/ptrace.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/static_call.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/fpu/regset.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/fpu/signal.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/fpu/bugs.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/resource.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/kdebugfs.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/fpu/init.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/irqflags.S
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/process.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/io_delay.c
        ${CMAKE_SOURCE_DIR}/arch/x86/events/zhaoxin/core.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/rtc.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/tsc_msr.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/tsc.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/hw_breakpoint.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/alternative.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/i8253.c
        ${CMAKE_SOURCE_DIR}/arch/x86/events/intel/uncore_snbep.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/bootflag.c
        ${CMAKE_SOURCE_DIR}/arch/x86/events/intel/cstate.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/quirks.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/pci-dma.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/e820.c
        ${CMAKE_SOURCE_DIR}/arch/x86/events/intel/uncore_discovery.c
        ${CMAKE_SOURCE_DIR}/arch/x86/events/intel/uncore_snb.c
        ${CMAKE_SOURCE_DIR}/arch/x86/events/intel/uncore_nhmex.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/ksysfs.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/espfix_64.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/sys_x86_64.c
        ${CMAKE_SOURCE_DIR}/arch/x86/mm/pti.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/signal_32.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/sys_ia32.c
        ${CMAKE_SOURCE_DIR}/arch/x86/lib/iomem.c
        ${CMAKE_SOURCE_DIR}/arch/x86/events/intel/uncore.c
        ${CMAKE_SOURCE_DIR}/arch/x86/events/intel/knc.c
        ${CMAKE_SOURCE_DIR}/arch/x86/mm/amdtopology.c
        ${CMAKE_SOURCE_DIR}/arch/x86/mm/kaslr.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/probe_roms.c
        ${CMAKE_SOURCE_DIR}/arch/x86/mm/pkeys.c
        ${CMAKE_SOURCE_DIR}/arch/x86/events/intel/pt.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/jump_label.c
        ${CMAKE_SOURCE_DIR}/arch/x86/events/intel/lbr.c
        ${CMAKE_SOURCE_DIR}/arch/x86/mm/srat.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/irq_work.c
        ${CMAKE_SOURCE_DIR}/arch/x86/events/intel/p6.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/setup.c
        ${CMAKE_SOURCE_DIR}/arch/x86/entry/syscall_32.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/irqinit.c
        ${CMAKE_SOURCE_DIR}/arch/x86/mm/numa_64.c
        ${CMAKE_SOURCE_DIR}/arch/x86/mm/numa.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/i8259.c
        ${CMAKE_SOURCE_DIR}/arch/x86/events/intel/p4.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/x86_init.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/ibt_selftest.S
        ${CMAKE_SOURCE_DIR}/arch/x86/entry/vdso/vdso-image-32.c
        ${CMAKE_SOURCE_DIR}/arch/x86/mm/dump_pagetables.c
        ${CMAKE_SOURCE_DIR}/arch/x86/lib/inat.c
        ${CMAKE_SOURCE_DIR}/arch/x86/entry/vdso/vdso-image-64.c
        ${CMAKE_SOURCE_DIR}/arch/x86/tools/relocs_64.c
        ${CMAKE_SOURCE_DIR}/arch/x86/lib/hweight.S
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/ioport.c
        ${CMAKE_SOURCE_DIR}/arch/x86/events/intel/ds.c
        ${CMAKE_SOURCE_DIR}/arch/x86/mm/pat/memtype_interval.c
        ${CMAKE_SOURCE_DIR}/arch/x86/entry/entry_64_compat.S
        ${CMAKE_SOURCE_DIR}/arch/x86/lib/msr-reg-export.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/ldt.c
        ${CMAKE_SOURCE_DIR}/arch/x86/lib/msr.c
        ${CMAKE_SOURCE_DIR}/arch/x86/lib/msr-reg.S
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/nmi.c
        ${CMAKE_SOURCE_DIR}/arch/x86/mm/hugetlbpage.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/dumpstack.c
        ${CMAKE_SOURCE_DIR}/arch/x86/mm/pat/set_memory.c
        ${CMAKE_SOURCE_DIR}/arch/x86/lib/cache-smp.c
        ${CMAKE_SOURCE_DIR}/arch/x86/entry/vdso/vdso32-setup.c
        ${CMAKE_SOURCE_DIR}/arch/x86/mm/pat/memtype.c
        ${CMAKE_SOURCE_DIR}/arch/x86/events/intel/bts.c
        ${CMAKE_SOURCE_DIR}/arch/x86/entry/vdso/vdso32/vgetcpu.c
        ${CMAKE_SOURCE_DIR}/arch/x86/events/intel/core.c
        ${CMAKE_SOURCE_DIR}/arch/x86/events/amd/iommu.c
        ${CMAKE_SOURCE_DIR}/arch/x86/realmode/rm/video-vesa.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/dumpstack_64.c
        ${CMAKE_SOURCE_DIR}/arch/x86/entry/vdso/vdso32/system_call.S
        ${CMAKE_SOURCE_DIR}/arch/x86/mm/pgprot.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/time.c
        ${CMAKE_SOURCE_DIR}/arch/x86/entry/vdso/vdso32/vclock_gettime.c
        ${CMAKE_SOURCE_DIR}/arch/x86/entry/vdso/vdso32/sigreturn.S
        ${CMAKE_SOURCE_DIR}/arch/x86/lib/usercopy_64.c
        ${CMAKE_SOURCE_DIR}/arch/x86/entry/vdso/vdso2c.c
        ${CMAKE_SOURCE_DIR}/arch/x86/pci/amd_bus.c
        ${CMAKE_SOURCE_DIR}/arch/x86/entry/vdso/vdso32/note.S
        ${CMAKE_SOURCE_DIR}/arch/x86/mm/maccess.c
        ${CMAKE_SOURCE_DIR}/arch/x86/lib/retpoline.S
        ${CMAKE_SOURCE_DIR}/arch/x86/lib/putuser.S
        ${CMAKE_SOURCE_DIR}/arch/x86/lib/usercopy.c
        ${CMAKE_SOURCE_DIR}/arch/x86/events/amd/uncore.c
        ${CMAKE_SOURCE_DIR}/arch/x86/mm/cpu_entry_area.c
        ${CMAKE_SOURCE_DIR}/arch/x86/lib/pc-conf-reg.c
        ${CMAKE_SOURCE_DIR}/arch/x86/entry/vdso/vclock_gettime.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/irq.c
        ${CMAKE_SOURCE_DIR}/arch/x86/entry/thunk.S
        ${CMAKE_SOURCE_DIR}/arch/x86/lib/memmove_64.S
        ${CMAKE_SOURCE_DIR}/arch/x86/lib/memset_64.S
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/irq_64.c
        ${CMAKE_SOURCE_DIR}/arch/x86/lib/misc.c
        ${CMAKE_SOURCE_DIR}/arch/x86/entry/vdso/vgetrandom-chacha.S
        ${CMAKE_SOURCE_DIR}/arch/x86/events/amd/lbr.c
        ${CMAKE_SOURCE_DIR}/arch/x86/events/amd/ibs.c
        ${CMAKE_SOURCE_DIR}/arch/x86/lib/memcpy_64.S
        ${CMAKE_SOURCE_DIR}/arch/x86/entry/vdso/vgetcpu.c
        ${CMAKE_SOURCE_DIR}/arch/x86/entry/vdso/vgetrandom.c
        ${CMAKE_SOURCE_DIR}/arch/x86/pci/bus_numa.c
        ${CMAKE_SOURCE_DIR}/arch/x86/entry/vsyscall/vsyscall_64.c
        ${CMAKE_SOURCE_DIR}/arch/x86/mm/tlb.c
        ${CMAKE_SOURCE_DIR}/arch/x86/entry/vsyscall/vsyscall_emu_64.S
        ${CMAKE_SOURCE_DIR}/arch/x86/events/msr.c
        ${CMAKE_SOURCE_DIR}/arch/x86/lib/insn-eval.c
        ${CMAKE_SOURCE_DIR}/arch/x86/lib/insn.c
        ${CMAKE_SOURCE_DIR}/arch/x86/lib/kaslr.c
        ${CMAKE_SOURCE_DIR}/arch/x86/entry/vdso/vdso-note.S
        ${CMAKE_SOURCE_DIR}/arch/x86/platform/intel/iosf_mbi.c
        ${CMAKE_SOURCE_DIR}/arch/x86/mm/pgtable.c
        ${CMAKE_SOURCE_DIR}/arch/x86/platform/efi/runtime-map.c
        ${CMAKE_SOURCE_DIR}/arch/x86/pci/early.c
        ${CMAKE_SOURCE_DIR}/arch/x86/events/amd/core.c
        ${CMAKE_SOURCE_DIR}/arch/x86/mm/physaddr.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/idt.c
        ${CMAKE_SOURCE_DIR}/arch/x86/platform/efi/efi_thunk_64.S
        ${CMAKE_SOURCE_DIR}/arch/x86/realmode/rmpiggy.S
        ${CMAKE_SOURCE_DIR}/arch/x86/platform/efi/efi_stub_64.S
        ${CMAKE_SOURCE_DIR}/arch/x86/lib/csum-copy_64.S
        ${CMAKE_SOURCE_DIR}/arch/x86/pci/irq.c
        ${CMAKE_SOURCE_DIR}/arch/x86/mm/mmap.c
        ${CMAKE_SOURCE_DIR}/arch/x86/lib/delay.c
        ${CMAKE_SOURCE_DIR}/arch/x86/pci/common.c
        ${CMAKE_SOURCE_DIR}/arch/x86/lib/getuser.S
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/signal_64.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/traps.c
        ${CMAKE_SOURCE_DIR}/arch/x86/entry/vdso/extable.c
        ${CMAKE_SOURCE_DIR}/arch/x86/pci/legacy.c
        ${CMAKE_SOURCE_DIR}/arch/x86/entry/vdso/vma.c
        ${CMAKE_SOURCE_DIR}/arch/x86/lib/csum-wrappers_64.c
        ${CMAKE_SOURCE_DIR}/arch/x86/pci/acpi.c
        ${CMAKE_SOURCE_DIR}/arch/x86/events/rapl.c
        ${CMAKE_SOURCE_DIR}/arch/x86/platform/efi/efi_64.c
        ${CMAKE_SOURCE_DIR}/arch/x86/lib/csum-partial_64.c
        ${CMAKE_SOURCE_DIR}/arch/x86/realmode/rm/video-bios.c
        ${CMAKE_SOURCE_DIR}/arch/x86/power/cpu.c
        ${CMAKE_SOURCE_DIR}/arch/x86/video/video-common.c
        ${CMAKE_SOURCE_DIR}/arch/x86/pci/i386.c
        ${CMAKE_SOURCE_DIR}/arch/x86/realmode/rm/copy.S
        ${CMAKE_SOURCE_DIR}/arch/x86/realmode/rm/bioscall.S
        ${CMAKE_SOURCE_DIR}/arch/x86/realmode/rm/regs.c
        ${CMAKE_SOURCE_DIR}/arch/x86/mm/extable.c
        ${CMAKE_SOURCE_DIR}/arch/x86/lib/cpu.c
        ${CMAKE_SOURCE_DIR}/arch/x86/events/probe.c
        ${CMAKE_SOURCE_DIR}/arch/x86/power/hibernate.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/process_64.c
        ${CMAKE_SOURCE_DIR}/arch/x86/events/utils.c
        ${CMAKE_SOURCE_DIR}/arch/x86/platform/efi/efi.c
        ${CMAKE_SOURCE_DIR}/arch/x86/realmode/rm/video-vga.c
        ${CMAKE_SOURCE_DIR}/arch/x86/mm/ioremap.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/signal.c
        ${CMAKE_SOURCE_DIR}/arch/x86/pci/fixup.c
        ${CMAKE_SOURCE_DIR}/arch/x86/power/hibernate_asm_64.S
        ${CMAKE_SOURCE_DIR}/arch/x86/pci/direct.c
        ${CMAKE_SOURCE_DIR}/arch/x86/pci/mmconfig-shared.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/platform-quirks.c
        ${CMAKE_SOURCE_DIR}/arch/x86/lib/copy_user_64.S
        ${CMAKE_SOURCE_DIR}/arch/x86/lib/copy_user_uncached_64.S
        ${CMAKE_SOURCE_DIR}/arch/x86/lib/clear_page_64.S
        ${CMAKE_SOURCE_DIR}/arch/x86/lib/copy_page_64.S
        ${CMAKE_SOURCE_DIR}/arch/x86/pci/mmconfig_64.c
        ${CMAKE_SOURCE_DIR}/arch/x86/entry/common.c
        ${CMAKE_SOURCE_DIR}/arch/x86/platform/efi/quirks.c
        ${CMAKE_SOURCE_DIR}/arch/x86/realmode/rm/wakeup_asm.S
        ${CMAKE_SOURCE_DIR}/arch/x86/realmode/rm/wakemain.c
        ${CMAKE_SOURCE_DIR}/arch/x86/realmode/rm/video-mode.c
        ${CMAKE_SOURCE_DIR}/arch/x86/mm/fault.c
        ${CMAKE_SOURCE_DIR}/arch/x86/mm/init_64.c
        ${CMAKE_SOURCE_DIR}/arch/x86/power/hibernate_64.c
        ${CMAKE_SOURCE_DIR}/arch/x86/realmode/rm/reboot.S
        ${CMAKE_SOURCE_DIR}/arch/x86/lib/copy_mc_64.S
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/asm-offsets.c
        ${CMAKE_SOURCE_DIR}/arch/x86/events/core.c
        ${CMAKE_SOURCE_DIR}/arch/x86/entry/entry.S
        ${CMAKE_SOURCE_DIR}/arch/x86/realmode/rm/stack.S
        ${CMAKE_SOURCE_DIR}/arch/x86/lib/copy_mc.c
        ${CMAKE_SOURCE_DIR}/arch/x86/pci/init.c
        ${CMAKE_SOURCE_DIR}/arch/x86/realmode/init.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/ebda.c
        ${CMAKE_SOURCE_DIR}/arch/x86/realmode/rm/trampoline_64.S
        ${CMAKE_SOURCE_DIR}/arch/x86/mm/init.c
        ${CMAKE_SOURCE_DIR}/arch/x86/ia32/audit.c
        ${CMAKE_SOURCE_DIR}/arch/x86/lib/cmdline.c
        ${CMAKE_SOURCE_DIR}/arch/x86/entry/entry_64.S
        ${CMAKE_SOURCE_DIR}/arch/x86/lib/cmpxchg16b_emu.S
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/head64.c
        ${CMAKE_SOURCE_DIR}/arch/x86/entry/syscall_64.c
        ${CMAKE_SOURCE_DIR}/arch/x86/kernel/head_64.S
        ${CMAKE_SOURCE_DIR}/arch/x86/realmode/rm/header.S
        ${CMAKE_SOURCE_DIR}/arch/x86/platform/efi/memmap.c
)