file(GLOB SCRIPTS_SRC
        ${CMAKE_SOURCE_DIR}/scripts/asn1_compiler.c
        ${CMAKE_SOURCE_DIR}/scripts/selinux/genheaders/genheaders.c
        ${CMAKE_SOURCE_DIR}/scripts/selinux/mdp/mdp.c
        ${CMAKE_SOURCE_DIR}/scripts/mod/mk_elfconfig.c
        ${CMAKE_SOURCE_DIR}/scripts/mod/devicetable-offsets.c
        ${CMAKE_SOURCE_DIR}/scripts/mod/empty.c
        ${CMAKE_SOURCE_DIR}/scripts/mod/symsearch.c
        ${CMAKE_SOURCE_DIR}/scripts/mod/modpost.c
        ${CMAKE_SOURCE_DIR}/scripts/mod/sumversion.c
        ${CMAKE_SOURCE_DIR}/scripts/mod/file2alias.c
        ${CMAKE_SOURCE_DIR}/scripts/kallsyms.c
        ${CMAKE_SOURCE_DIR}/scripts/sorttable.c
        ${CMAKE_SOURCE_DIR}/scripts/basic/fixdep.c
)
set_source_files_properties(${CMAKE_SOURCE_DIR}/scripts/asn1_compiler.c PROPERTIES COMPILE_FLAGS "-c -Wp,-MMD,${CMAKE_SOURCE_DIR}/scripts/.asn1_compiler.d -Wall -Wmissing-prototypes -Wstrict-prototypes -O2 -fomit-frame-pointer -std=gnu11 -I../ ./scripts/include -I.././include")
set_source_files_properties(${CMAKE_SOURCE_DIR}/scripts/basic/fixdep.c PROPERTIES COMPILE_FLAGS "-c -Wp,-MMD,${CMAKE_SOURCE_DIR}/scripts/basic/.fixdep.d -Wall -Wmissing-prototypes -Wstrict-prototypes -O2 -fomit-frame-pointer -std=gnu11 -I../ ./scripts/include")
set_source_files_properties(${CMAKE_SOURCE_DIR}/scripts/kallsyms.c PROPERTIES COMPILE_FLAGS "-c -Wp,-MMD,${CMAKE_SOURCE_DIR}/scripts/.kallsyms.d -Wall -Wmissing-prototypes -Wstrict-prototypes -O2 -fomit-frame-pointer -std=gnu11 -I../ ./scripts/include")
set_source_files_properties(${CMAKE_SOURCE_DIR}/scripts/mod/devicetable-offsets.c PROPERTIES COMPILE_FLAGS "-Wp,-MMD,${CMAKE_SOURCE_DIR}/scripts/mod/.devicetable-offsets.s.d -nostdinc -I.././arch/x86/include -I.././arch/x86/include/generated -I.././include -I.././arch/x86/include/uapi -I.././arch/x86/include/generated/uapi -I.././include/uapi -I.././include/generated/uapi -include .././include/linux/compiler-version.h -include .././include/linux/kconfig.h -include .././include/linux/compiler_types.h -D__KERNEL__ -fmacro-prefix-map=./= -Werror -std=gnu11 -fshort-wchar -funsigned-char -fno-common -fno-PIE -fno-strict-aliasing -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -fcf-protection=branch -fno-jump-tables -m64 -falign-jumps=1 -falign-loops=1 -mno-80387 -mno-fp-ret-in-387 -mpreferred-stack-boundary=3 -mskip-rax-setup -mtune=generic -mno-red-zone -mcmodel=kernel -Wno-sign-compare -fno-asynchronous-unwind-tables -mindirect-branch=thunk-extern -mindirect-branch-register -mindirect-branch-cs-prefix -mfunction-return=thunk-extern -fno-jump-tables -fpatchable-function-entry=16,16 -fno-delete-null-pointer-checks -O2 -fno-allow-store-data-races -fstack-protector-strong -fomit-frame-pointer -ftrivial-auto-var-init=zero -fno-stack-clash-protection -fmin-function-alignment=16 -fstrict-flex-arrays=3 -fno-strict-overflow -fno-stack-check -fconserve-stack -Wall -Wundef -Werror=implicit-function-declaration -Werror=implicit-int -Werror=return-type -Werror=strict-prototypes -Wno-format-security -Wno-trigraphs -Wno-frame-address -Wno-address-of-packed-member -Wmissing-declarations -Wmissing-prototypes -Wframe-larger-than=2048 -Wno-main -Wno-dangling-pointer -Wvla -Wno-pointer-sign -Wcast-function-type -Wno-stringop-overflow -Wno-array-bounds -Wno-alloc-size-larger-than -Wimplicit-fallthrough=5 -Werror=date-time -Werror=incompatible-pointer-types -Werror=designated-init -Wenum-conversion -Wextra -Wunused -Wno-unused-but-set-variable -Wno-unused-const-variable -Wno-packed-not-aligned -Wno-format-overflow -Wno-format-truncation -Wno-stringop-truncation -Wno-override-init -Wno-missing-field-initializers -Wno-type-limits -Wno-shift-negative-value -Wno-maybe-uninitialized -Wno-sign-compare -Wno-unused-parameter -DKBUILD_MODFILE=\\\"scripts/mod/devicetable-offsets\\\" -DKBUILD_BASENAME=\\\"devicetable_offsets\\\" -DKBUILD_MODNAME=\\\"devicetable_offsets\\\" -D__KBUILD_MODNAME=kmod_devicetable_offsets -fverbose-asm -S")
set_source_files_properties(${CMAKE_SOURCE_DIR}/scripts/mod/empty.c PROPERTIES COMPILE_FLAGS "-Wp,-MMD,${CMAKE_SOURCE_DIR}/scripts/mod/.empty.o.d -nostdinc -I.././arch/x86/include -I.././arch/x86/include/generated -I.././include -I.././arch/x86/include/uapi -I.././arch/x86/include/generated/uapi -I.././include/uapi -I.././include/generated/uapi -include .././include/linux/compiler-version.h -include .././include/linux/kconfig.h -include .././include/linux/compiler_types.h -D__KERNEL__ -fmacro-prefix-map=./= -Werror -std=gnu11 -fshort-wchar -funsigned-char -fno-common -fno-PIE -fno-strict-aliasing -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -fcf-protection=branch -fno-jump-tables -m64 -falign-jumps=1 -falign-loops=1 -mno-80387 -mno-fp-ret-in-387 -mpreferred-stack-boundary=3 -mskip-rax-setup -mtune=generic -mno-red-zone -mcmodel=kernel -Wno-sign-compare -fno-asynchronous-unwind-tables -mindirect-branch=thunk-extern -mindirect-branch-register -mindirect-branch-cs-prefix -mfunction-return=thunk-extern -fno-jump-tables -fpatchable-function-entry=16,16 -fno-delete-null-pointer-checks -O2 -fno-allow-store-data-races -fstack-protector-strong -fomit-frame-pointer -ftrivial-auto-var-init=zero -fno-stack-clash-protection -fmin-function-alignment=16 -fstrict-flex-arrays=3 -fno-strict-overflow -fno-stack-check -fconserve-stack -Wall -Wundef -Werror=implicit-function-declaration -Werror=implicit-int -Werror=return-type -Werror=strict-prototypes -Wno-format-security -Wno-trigraphs -Wno-frame-address -Wno-address-of-packed-member -Wmissing-declarations -Wmissing-prototypes -Wframe-larger-than=2048 -Wno-main -Wno-dangling-pointer -Wvla -Wno-pointer-sign -Wcast-function-type -Wno-stringop-overflow -Wno-array-bounds -Wno-alloc-size-larger-than -Wimplicit-fallthrough=5 -Werror=date-time -Werror=incompatible-pointer-types -Werror=designated-init -Wenum-conversion -Wextra -Wunused -Wno-unused-but-set-variable -Wno-unused-const-variable -Wno-packed-not-aligned -Wno-format-overflow -Wno-format-truncation -Wno-stringop-truncation -Wno-override-init -Wno-missing-field-initializers -Wno-type-limits -Wno-shift-negative-value -Wno-maybe-uninitialized -Wno-sign-compare -Wno-unused-parameter -DKBUILD_MODFILE=\\\"scripts/mod/empty\\\" -DKBUILD_BASENAME=\\\"empty\\\" -DKBUILD_MODNAME=\\\"empty\\\" -D__KBUILD_MODNAME=kmod_empty -c")
set_source_files_properties(${CMAKE_SOURCE_DIR}/scripts/mod/file2alias.c PROPERTIES COMPILE_FLAGS "-Wp,-MMD,${CMAKE_SOURCE_DIR}/scripts/mod/.file2alias.o.d -Wall -Wmissing-prototypes -Wstrict-prototypes -O2 -fomit-frame-pointer -std=gnu11 -I../ ./scripts/include -c")
set_source_files_properties(${CMAKE_SOURCE_DIR}/scripts/mod/mk_elfconfig.c PROPERTIES COMPILE_FLAGS "-c -Wp,-MMD,${CMAKE_SOURCE_DIR}/scripts/mod/.mk_elfconfig.d -Wall -Wmissing-prototypes -Wstrict-prototypes -O2 -fomit-frame-pointer -std=gnu11 -I../ ./scripts/include")
set_source_files_properties(${CMAKE_SOURCE_DIR}/scripts/mod/modpost.c PROPERTIES COMPILE_FLAGS "-Wp,-MMD,${CMAKE_SOURCE_DIR}/scripts/mod/.modpost.o.d -Wall -Wmissing-prototypes -Wstrict-prototypes -O2 -fomit-frame-pointer -std=gnu11 -I../ ./scripts/include -c")
set_source_files_properties(${CMAKE_SOURCE_DIR}/scripts/mod/sumversion.c PROPERTIES COMPILE_FLAGS "-Wp,-MMD,${CMAKE_SOURCE_DIR}/scripts/mod/.sumversion.o.d -Wall -Wmissing-prototypes -Wstrict-prototypes -O2 -fomit-frame-pointer -std=gnu11 -I../ ./scripts/include -c")
set_source_files_properties(${CMAKE_SOURCE_DIR}/scripts/mod/symsearch.c PROPERTIES COMPILE_FLAGS "-Wp,-MMD,${CMAKE_SOURCE_DIR}/scripts/mod/.symsearch.o.d -Wall -Wmissing-prototypes -Wstrict-prototypes -O2 -fomit-frame-pointer -std=gnu11 -I../ ./scripts/include -c")
set_source_files_properties(${CMAKE_SOURCE_DIR}/scripts/selinux/genheaders/genheaders.c PROPERTIES COMPILE_FLAGS "-c -Wp,-MMD,${CMAKE_SOURCE_DIR}/scripts/selinux/genheaders/.genheaders.d -Wall -Wmissing-prototypes -Wstrict-prototypes -O2 -fomit-frame-pointer -std=gnu11 -I../ ./scripts/include -I.././include/uapi -I.././include -I.././security/selinux/include")
set_source_files_properties(${CMAKE_SOURCE_DIR}/scripts/selinux/mdp/mdp.c PROPERTIES COMPILE_FLAGS "-c -Wp,-MMD,${CMAKE_SOURCE_DIR}/scripts/selinux/mdp/.mdp.d -Wall -Wmissing-prototypes -Wstrict-prototypes -O2 -fomit-frame-pointer -std=gnu11 -I../ ./scripts/include -I.././include/uapi -I.././include -I.././security/selinux/include -I.././include")
set_source_files_properties(${CMAKE_SOURCE_DIR}/scripts/sorttable.c PROPERTIES COMPILE_FLAGS "-c -Wp,-MMD,${CMAKE_SOURCE_DIR}/scripts/.sorttable.d -Wall -Wmissing-prototypes -Wstrict-prototypes -O2 -fomit-frame-pointer -std=gnu11 -I../ ./scripts/include -I.././tools/include -I.././tools/arch/x86/include -DUNWINDER_ORC_ENABLED")
